#!/bin/bash
set -euo pipefail

# GitHub PR creation wrapper with validations
# Usage: ./create-pr.sh <branch-name> <title> <description> [base-branch]
# Based on: docs/standards/tool-integrations.md

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >&2
}

error() {
    log "ERROR: $*"
    exit 1
}

validate_input() {
    [[ $# -ge 3 ]] || error "Usage: $0 <branch-name> <title> <description> [base-branch]"
    [[ -n "$1" ]] || error "Branch name cannot be empty"
    [[ -n "$2" ]] || error "PR title cannot be empty"
    [[ -n "$3" ]] || error "PR description cannot be empty"
}

check_dependencies() {
    command -v gh >/dev/null 2>&1 || error "GitHub CLI (gh) is required but not installed"
    command -v git >/dev/null 2>&1 || error "Git is required but not installed"
}

validate_git_state() {
    # Check if we're in a git repository
    git rev-parse --git-dir >/dev/null 2>&1 || error "Not in a git repository"

    # Check if current branch matches specified branch
    CURRENT_BRANCH=$(git branch --show-current)
    if [[ "$CURRENT_BRANCH" != "$BRANCH_NAME" ]]; then
        error "Current branch '$CURRENT_BRANCH' doesn't match specified branch '$BRANCH_NAME'"
    fi

    # Check if there are uncommitted changes
    if ! git diff-index --quiet HEAD --; then
        error "There are uncommitted changes. Please commit or stash them first."
    fi

    # Check if branch has commits ahead of base
    AHEAD_COUNT=$(git rev-list --count "${BASE_BRANCH}..${BRANCH_NAME}" 2>/dev/null || echo "0")
    if [[ "$AHEAD_COUNT" == "0" ]]; then
        error "Branch '$BRANCH_NAME' has no commits ahead of '$BASE_BRANCH'"
    fi

    log "Branch validation passed: $AHEAD_COUNT commits ahead of $BASE_BRANCH"
}

generate_pr_template() {
    local title="$1"
    local description="$2"

    cat << EOF
$title

## Summary
$description

## Changes Made
$(git log --oneline "${BASE_BRANCH}..${BRANCH_NAME}" | sed 's/^/- /')

## Testing
- [ ] Unit tests pass
- [ ] Integration tests pass
- [ ] Manual testing completed

## Code Review Checklist
- [ ] Code follows project conventions
- [ ] Documentation updated if needed
- [ ] Breaking changes documented
- [ ] Security considerations addressed

## Related Issues
<!-- Link any related Jira tickets or GitHub issues -->

---
*Generated by create-pr.sh script*
EOF
}

# Main execution
validate_input "$@"
check_dependencies

BRANCH_NAME="$1"
PR_TITLE="$2"
PR_DESCRIPTION="$3"
BASE_BRANCH="${4:-develop}"

log "Creating PR from '$BRANCH_NAME' to '$BASE_BRANCH'"

# Validate git state
validate_git_state

# Check if branch exists on remote
log "Checking remote branch status..."
if ! git ls-remote --exit-code --heads origin "$BRANCH_NAME" >/dev/null 2>&1; then
    log "Branch not found on remote, pushing..."
    git push -u origin "$BRANCH_NAME" || error "Failed to push branch to remote"
else
    log "Branch exists on remote, ensuring it's up to date..."
    git push origin "$BRANCH_NAME" || error "Failed to update remote branch"
fi

# Generate PR body
PR_BODY=$(generate_pr_template "$PR_TITLE" "$PR_DESCRIPTION")

# Create temporary file for PR body
TEMP_FILE=$(mktemp)
trap "rm -f $TEMP_FILE" EXIT
echo "$PR_BODY" > "$TEMP_FILE"

# Check if PR already exists
log "Checking for existing PRs..."
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --base "$BASE_BRANCH" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [[ -n "$EXISTING_PR" ]]; then
    log "PR #$EXISTING_PR already exists for this branch"
    log "Updating existing PR..."
    gh pr edit "$EXISTING_PR" --title "$PR_TITLE" --body-file "$TEMP_FILE"
    PR_URL=$(gh pr view "$EXISTING_PR" --json url --jq '.url')
    log "✅ Updated existing PR: $PR_URL"
else
    # Create new PR
    log "Creating new PR..."
    PR_URL=$(gh pr create \
        --title "$PR_TITLE" \
        --body-file "$TEMP_FILE" \
        --base "$BASE_BRANCH" \
        --head "$BRANCH_NAME")

    if [[ $? -eq 0 ]]; then
        log "✅ Successfully created PR: $PR_URL"
    else
        error "Failed to create PR"
    fi
fi

# Add labels if Jira ticket is detected in branch name
if [[ "$BRANCH_NAME" =~ (PROJ|SDLC)-[0-9]+ ]]; then
    TICKET_ID="${BASH_REMATCH[0]}"
    log "Detected Jira ticket: $TICKET_ID"
    gh pr edit "$PR_URL" --add-label "jira:$TICKET_ID" 2>/dev/null || log "WARN: Could not add Jira label"
fi

# Output summary
echo "PR_URL=$PR_URL"
echo "BRANCH=$BRANCH_NAME"
echo "BASE=$BASE_BRANCH"
echo "COMMITS=$(git rev-list --count "${BASE_BRANCH}..${BRANCH_NAME}")"

log "PR creation completed successfully"